targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: "DataSource$|UseCase$|Navigator$|Bloc$|Cubit$"
          file_name_pattern: "_data_source$|_use_case$|_navigator$|_bloc$|_cubit$"