targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: "DataSource$|Bloc$"
          file_name_pattern: "_data_source$|_bloc$"