name: Baby List - Web Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  web-continuous-delivery:
    name: Web Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get packages
        run: flutter pub get
      - name: Execute build runner
        run: flutter pub run build_runner build
      - name: Build release version
        run: flutter build web --release
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web